name: 'Build'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - uses: abatilo/actions-poetry@v3
      with:
        poetry-version: "latest"

    - name: Install dependencies
      run: poetry install

    - name: Build
      run: poetry build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

