name: release

on:
  push:
    branches:
      - main

jobs:
  test_and_build:
    uses: ./.github/workflows/test_and_build.yml
  release:
    runs-on: ubuntu-latest
    needs:
      - test_and_build
    environment:
      name: pypi
      url: https://pypi.org/p/pytest-mitmproxy-plugin
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.test_and_build.outputs.version }}
          tag_exists_error: false
          message: "Release ${{ needs.test_and_build.outputs.version }}"
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: create-release
        uses: softprops/action-gh-release@v2
        id: create_release
        with:
          draft: false
          prerelease: false
          name: "Release ${{ needs.test_and_build.outputs.version }}"
          body: ${{ github.event.head_commit.message }}
          tag_name: ${{ needs.test_and_build.outputs.version }}
          files: 'dist/*'
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
