name: release

on:
  push:
    branches:
      - main

jobs:
  test_and_build:
    uses: ./.github/workflows/test_and_build.yml
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/p/pytest-mitmproxy-plugin
    permissions:
      id-token: write
    steps:
      - name: create-release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ needs.build.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
